.PHONY: clean All

All:
	@echo "----------Building project:[ Hash - Debug ]----------"
	@"$(MAKE)" -f  "Hash.mk"
clean:
	@echo "----------Cleaning project:[ Hash - Debug ]----------"
	@"$(MAKE)" -f  "Hash.mk" clean
