.PHONY: clean All

All:
	@echo "----------Building project:[ GNA - Debug ]----------"
	@"$(MAKE)" -f  "GNA.mk"
clean:
	@echo "----------Cleaning project:[ GNA - Debug ]----------"
	@"$(MAKE)" -f  "GNA.mk" clean
